{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "http-monitoring.serviceAccountName" . }}
  labels:
    {{- include "http-monitoring.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: {{ include "http-monitoring.serviceAccountName" . }}
  labels:
    {{- include "http-monitoring.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: http-monitoring
subjects:
  - kind: ServiceAccount
    name: http-monitoring
    namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: {{ include "http-monitoring.serviceAccountName" . }}
  labels:
    {{- include "http-monitoring.labels" . | nindent 4 }}
  {{- with .Values.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["watch"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["watch"]
{{- end }}