apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-monitoring
  labels:
    app.kubernetes.io/name: http-monitoring
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: http-monitoring
  template:
    metadata:
      labels:
        app.kubernetes.io/name: http-monitoring
    spec:
      serviceAccountName: http-monitoring
      securityContext:
        {}
      containers:
        - name: http-monitoring
          securityContext:
            {}
          image: "kj187/http-monitoring:latest"
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
          resources:
            {}
