apiVersion: v1
kind: ServiceAccount
metadata:
  name: http-monitoring
  labels:
    app.kubernetes.io/name: http-monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: http-monitoring
  labels:
    app.kubernetes.io/name: http-monitoring
rules:
  - apiGroups: [""]
    resources: ["namespaces"]
    verbs: ["list"]
  - apiGroups: [""]
    resources: ["services"]
    verbs: ["watch"]
  - apiGroups: ["extensions"]
    resources: ["ingresses"]
    verbs: ["watch"]
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRoleBinding
metadata:
  name: http-monitoring
  labels:
    app.kubernetes.io/name: http-monitoring
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: http-monitoring
subjects:
  - kind: ServiceAccount
    name: http-monitoring
    namespace: default